name: contact_mvc
version: 0.0.1
author: Evèssèhou Moïse Dovonou <dovonoumoise@yahoo.fr>
description: contact_mvc application for contacts management. dartling is a domain model framework. DWT is a web framework.
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
  dart_web_toolkit: any
  dartling: '>=1.0.1 <2.0.0'
  dartling_default_app: '>=1.0.1 <2.0.0'



  